CUDA_VISIBLE_DEVICES=1 python ../../../learn.py\
    --data_path_prefix ../../../../data/multiwoz/data/\
    --data_version 2.3\
    --model_name t5-small\
    --pretrained_path ../../../../checkpoints/small/\
    --ckpt_save_path ../../../ckpt23/small/few_shot_0.01_augx1/\
    --use_db_as_input True\
    --epoch_num 50\
    --gradient_accumulation_steps 2\
    --number_of_gpu 1\
    --batch_size_per_gpu 32\
    --train_data_ratio 0.01\
    --aug_train_data_file multi-woz-fine-processed-train-combine0.2_2_shot_augment_dialog_turn_info_train_ratio_0.01_simulation_result.json